name: Build and run integration tests

on:
  push:
    branches: [ "staging" ]

jobs:
  build_run_integration_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Integration Tests
      run: dotnet test HouseRentingSystem.Tests/HouseRentingSystem.Tests.csproj --no-build --verbosity normal
